image: openjdk:8

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_BUILD_REF_NAME}"
  PROJECTNAME: gMark
  VERSION: ${CI_COMMIT_REF_NAME}

before_script:
  - java -version
  - chmod -R 755 ./*
  - cd ${PROJECTNAME}
  - ls -l

stages:
  - check
  - compile
  - test
  - status
  - javadoc
  - publishing
  
endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - mkdir ../javadoc
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :javadoc
    - mv ./build/docs/javadoc/* ../javadoc/
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker build -t gmark .
  stage: compile

compile:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} clientJar
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} createExe
    - mv ./build/libs/* ../
    - mv ./build/launch4j/*.exe ../
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-*.jar
      - ${PROJECTNAME}-*.exe

test:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml

publish:
  script:
    - ./gradlew publishAllPublicationsToMavenRepository
  only: 
    - tags
  when: manual
  allow_failure: false
  stage: publishing