image: eclipse-temurin:17

variables:
  SUFFIX: "${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}"
  PROJECTNAME: gMark

before_script:
  - java -version
  - cd ${PROJECTNAME}
  - ls -l
  - chmod -R 755 ./*

stages:
  - check
  - compile
  - test
  - status
  - javadoc
  - publishing

endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

sonar:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :sonar
  allow_failure: true
  stage: check
  only:
    - master

spotbugs:
  allow_failure: true
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :spotbugsAll
  stage: check
  artifacts:
    name: "SpotBugs-${SUFFIX}"
    expire_in: 1 week
    when: always
    paths:
      - ./${PROJECTNAME}/build/reports/spotbugs/main/spotbugs.html

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :javadocAll
    - mv ./build/javadoc ../
  stage: javadoc
  artifacts:
    name: "Javadoc-${SUFFIX}"
    expire_in: 1 week
    paths:
      - javadoc/

cli:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} cli:shadowJar
    - mv ./cli/build/libs/*.jar ../gMark.jar
  stage: compile
  artifacts:
    name: gMark-CLI-${SUFFIX}
    expire_in: 1 week
    paths:
      - gMark.jar

client:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} client:shadowJar
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} client:createExe
    - mv ./client/build/libs/* ..
    - mv ./client/build/launch4j/*.exe ..
  stage: compile
  artifacts:
    name: gMark-Client-${SUFFIX}
    expire_in: 1 week
    paths:
      - gMark-*.jar
      - gMark-*.exe

compile:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :jar
    - mv ./build/libs/*.jar ../gMark.jar
  stage: compile
  artifacts:
    name: gMark-${SUFFIX}
    expire_in: 1 week
    paths:
      - gMark.jar

test:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml

publish:
  script: ./gradlew -PrefName=${CI_COMMIT_REF_NAME} publishAllPublicationsToMavenRepository
  only:
    - tags
  when: manual
  allow_failure: false
  stage: publishing
