image: openjdk:8

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_BUILD_REF_NAME}"
  PROJECTNAME: gMark

before_script:
  - java -version
  - chmod -R 755 ./*
  - cd ${PROJECTNAME}
  - ls -l

stages:
  - check
  - compile
  - test
  - javadoc
  
endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - mkdir ../javadoc
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :javadoc
    - mv ./build/docs/javadoc/* ../javadoc/
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker build -t gmark .
  stage: compile

compile:
  script: curl ${SERVER}ci/publish.sh | bash
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}.jar

test:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml
