image: eclipse-temurin:17

variables:
  NAME: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_BUILD_REF_NAME}"
  PROJECTNAME: gMark

before_script:
  - java -version
  - chmod -R 755 ./*
  - cd ${PROJECTNAME}
  - ls -l

stages:
  - check
  - compile
  - test
  - status
  - javadoc
  - publishing
  
endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

spotbugs:
  allow_failure: true
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :spotbugsClient
  stage: check
  artifacts:
    name: "SpotBugs Report"
    expire_in: 1 week
    when: always
    paths:
      - ${PROJECTNAME}/build/reports/spotbugs/main/spotbugs.html

pending:
  allow_failure: true
  script: curl ${SERVER}ci/pending.sh | bash
  stage: compile

success:
  allow_failure: true
  script: curl ${SERVER}ci/success.sh | bash
  when: on_success
  stage: status

failure:
  allow_failure: true
  script: curl ${SERVER}ci/failure.sh | bash
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - mkdir ../javadoc
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :javadoc
    - mv ./build/docs/javadoc/* ../javadoc/
  stage: javadoc
  artifacts:
    name: "${NAME} [Javadoc]"
    expire_in: 1 week
    paths:
      - javadoc/

docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker info
    - docker build -t gmark .
  stage: compile

compile:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} clientJar
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} createExe
    - mv ./build/libs/* ../
    - mv ./build/launch4j/*.exe ../
  stage: compile
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-*.jar
      - ${PROJECTNAME}-*.exe

test:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml

maven:
  script:
    - ./gradlew publishAllPublicationsToMavenRepository
  only: 
    - tags
  when: manual
  allow_failure: false
  stage: publishing

hub:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker
  services:
    - docker:dind
  before_script: []
  needs: ["maven"]
  script:
    - docker info
    - docker build -t gmark .
    - docker tag gmark roanh/gmark:${CI_COMMIT_REF_NAME:1}
    - docker tag gmark roanh/gmark:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push roanh/gmark:${CI_COMMIT_REF_NAME:1}
    - docker push roanh/gmark:latest
  stage: publishing
  allow_failure: false
  only:
    - tags