image: eclipse-temurin:17

variables:
  SUFFIX: ${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}
  PROJECTNAME: QuickSilver

before_script:
  - java -version
  - cd ${PROJECTNAME}
  - ls -l
  - chmod -R 755 ./*

stages:
  - check
  - compile
  - test
  - javadoc

endings:
  allow_failure: true
  script: curl ${SERVER}ci/lf.sh | bash
  stage: check

verify:
  allow_failure: true
  script: curl ${SERVER}ci/javadoc.sh | bash
  stage: javadoc
  coverage: '/\([0-9]{2,3}\.[0-9]{2}%\)/'

javadoc:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} javadoc
    - mv ./build/docs/javadoc ../
  stage: javadoc
  artifacts:
    name: Javadoc-${SUFFIX}
    expire_in: 1 day
    paths:
      - javadoc/

compile:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :shadowJar
    - mv ./build/libs/*.jar ../QuickSilver.jar
  stage: compile
  artifacts:
    name: QuickSilver-${SUFFIX}
    expire_in: 1 day
    paths:
      - QuickSilver.jar

test:
  script:
    - ./gradlew -PrefName=${CI_COMMIT_REF_NAME} -PnexusPublic=${NEXUS_PUBLIC} :test :jacocoTestReport
    - cat ./build/reports/jacoco/test/html/index.html
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: ./${PROJECTNAME}/build/test-results/test/TEST-*.xml
