/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_cpqindex_Nauty */

#ifndef _Included_dev_roanh_cpqindex_Nauty
#define _Included_dev_roanh_cpqindex_Nauty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_cpqindex_Nauty
 * Method:    computeCanonSparse
 * Signature: ([[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_dev_roanh_cpqindex_Nauty_computeCanonSparse
  (JNIEnv *, jclass, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
